// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqY35OVkyKjIOkkOVN-ERZXK_bZMSjDEU',
    appId: '1:564305567496:web:ca79e186cfaec6748b56bd',
    messagingSenderId: '564305567496',
    projectId: 'apprestaurant-72f34',
    authDomain: 'apprestaurant-72f34.firebaseapp.com',
    storageBucket: 'apprestaurant-72f34.appspot.com',
    measurementId: 'G-B1M6WEWG8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-_yi0suSrqTXcNiwrfrt3QsqG04VIkcQ',
    appId: '1:564305567496:android:faca01948ffb3f798b56bd',
    messagingSenderId: '564305567496',
    projectId: 'apprestaurant-72f34',
    storageBucket: 'apprestaurant-72f34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_KBXC0mYCQtaUjxkfJCKvItc5mFJqjNk',
    appId: '1:564305567496:ios:f2c547b217143c608b56bd',
    messagingSenderId: '564305567496',
    projectId: 'apprestaurant-72f34',
    storageBucket: 'apprestaurant-72f34.appspot.com',
    iosBundleId: 'com.example.apprestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_KBXC0mYCQtaUjxkfJCKvItc5mFJqjNk',
    appId: '1:564305567496:ios:f2c547b217143c608b56bd',
    messagingSenderId: '564305567496',
    projectId: 'apprestaurant-72f34',
    storageBucket: 'apprestaurant-72f34.appspot.com',
    iosBundleId: 'com.example.apprestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqY35OVkyKjIOkkOVN-ERZXK_bZMSjDEU',
    appId: '1:564305567496:web:fd555709dab385a18b56bd',
    messagingSenderId: '564305567496',
    projectId: 'apprestaurant-72f34',
    authDomain: 'apprestaurant-72f34.firebaseapp.com',
    storageBucket: 'apprestaurant-72f34.appspot.com',
    measurementId: 'G-Q7CVTXHCHZ',
  );

}